Text_MayIHelpYou::
	.string "Hi, there!\n"
	.string "May I help you?$"

Text_FillOutQuestionnaire::
	.string "There is a questionnaire.\n"
	.string "Would you like to fill it out?$"

Text_QuestionnaireThankYou::
	.string "Thank you for taking the time to\n"
	.string "fill out our questionnaire.\p"
	.string "Your feedback will be used for\n"
	.string "future reference.$"

Text_YouKnowThoseWords::
	.string "Oh, hello!\n"
	.string "You know those words?\p"
	.string "That means you must know about\n"
	.string "NEW GAME PLUS.\p"
	.string "From now on, you should be able\n"
	.string "to use NEW GAME PLUS!$"

Text_YouCanAccessMysteryGift::
	.string "Once you save your game, you can\n"
	.string "access NEW GAME PLUS.$"

Text_ThankYouForAccessingMysteryGift::
	.string "Thank you for accessing\n"
	.string "NEW GAME PLUS.$"
